
const Map<String, String> ar = {
  "app_name": "Popcorn",
  "error_wrong": "حدث خطأ ما حاول مرة أخرى في وقت لاحق",
  "my_account": "حسابي",
  "sign_in": "تسجيل الدخول",
  "sign_in_google": "تسجيل الدخول باستخدام جوجل",
  "sign_in_facebook": "تسجيل الدخول باستخدام فيسبوك",
  "sign_with_email": "تسجيل الدخول باستخدام الايمايل",
  "sign_up_google": "تسجيل اشترك باستخدام جوجل",
  "sign_up_facebook": "تسجيل اشترك باستخدام فيسبوك",
  "something_wrong": "عفوا!، هناك خطأ ما",
  "welcome": "مرحبا %s",
  "line_or": "أو",
  "forgot_pass": "نسيت رقمك السري؟",
  "password": "كلمة المرور",
  "required_field": "حقل مطلوب",
  "required_field_for": "حقل مطلوب %s",
  "email_address": "عنوان البريد الإلكتروني",
  "user_not_found": "لم يتم العثور على مستخدم لهذا البريد الإلكتروني",
  "email_valid": "أدخل عنوان بريد إلكتروني صالح",
  "sign_up_free": "سجل مجانا",
  "new_account": "تسجيل حساب جديد",
  "your_name": "اسمك",
  "phone_number": "رقم تليفونك",
  "create_account": "إنشاء حساب",
  "cancel": "إلغاء",
  "weak_password": "كلمة المرور ضعيفة",
  "email_already_use": "الحساب موجود بالفعل لهذا البريد الإلكتروني",
  "pass_not_correct": "كلمة المرور غير صحيحة",
  "reset_pass": "إعادة تعيين كلمة المرور",
  "send_reset_link": "أرسل رابط إعادة التعيين",
  "send": "إرسال ",
  "check_email": "تحقق من عنوان بريدك الإلكتروني",
  "reset_password": "اعد ضبط كلمه السر",
  "home": "الرئيسية",
  "update_account": "تحديث الحساب",
  "update_success": "تم التحديث بنجاح",
  "old_pass": "كلمة السر قديمة",
  "new_pass": "كلمة السر الجديدة",
  "old_email": "عنوان البريد الإلكتروني القديم",
  "new_email": "عنوان البريد الإلكتروني الجديد",
  "update_email": "تحديث البريد الألكتروني",
  "update": "تحديث",
  "recent_login": "هذه العملية حساسة وتتطلب مصادقة حديثة. قم بتسجيل الدخول مرة أخرى قبل إعادة محاولة هذا الطلب.",
  "update_pass": "تحديث كلمة المرور",
  "old_pass_not_correct": "كلمة مرورك القديمة غير صحيحة",
  "next": "التالي",
  "back": "عودة",
  "select_photos": "حدد الصور",
  "select_photo": "اختر صورة",
  "price": "السعر",
  "error_connection": "لا يوجد اتصال بالإنترنت. تأكد من تشغيل Wi-Fi أو البيانات الخلوية ، ثم حاول مرة أخرى",
  "login_required": "تسجيل الدخول مطلوب",
  "delete_optional": "حذف اختياري",
  "delete": "حذف",
  "active_since": "نشط منذ %s",
  "my_favorite": "My Favorite",
  "search": "بحث",
  "not_found": "لم نتمكن من العثور على ما تبحث عنه",
  "validate": "تحقق",
  "filters": "فلتر",
  "all_photos": "كافة الصور",
  "email_invalid": "عنوان البريد الإلكتروني غير صالح",
  "login": "تسجيل الدخول",
  "sign_up": "اشتراك",
  "skip": "يتخطى",
  "get_start": "ابدأ الآن",
  "intro_1": "Hello! \uD83D\uDC4B",
  "intro_2": "App for those who are going through difficult times and can't share it with anyone",
  "intro_3": "Support \uD83D\uDE4F",
  "intro_4": "Support is something that helps you survive and not give up. Community inside the OutLoud can help to reduce feelings of loneliness and help you to feel understood",
  "intro_5": "Psychology \uD83E\uDDE0",
  "intro_6": "From a psychological point of view, writing out your problems and crisis situations helps you manage with them at least emotionally",
  "intro_7": "Anonymous \uD83E\uDDB8",
  "intro_8": "To keep incognito or openly talk about your problem - it's only up to you. Your anonymity is guaranteed",
  "dont_have_account":"لا تملك حسابا حتى الآن؟",
  "register": "انشاء حساب",
  "exit_app": "هل أنت متأكد من انك تريد الخروج؟",
  "logout_app": "Are you sure you want to Logout?",
  "no": "لا",
  "yes": "نعم",
  "account": "حسابي",
  "info": "معلومات",
  "favorite": "المفضل",
  "how_to_use":"كيف تستخدم بوب كورن؟",
  "category": "الفئة",
  "admin": "المشرف",
  "upload_images": "رفع الصور",
  "upload_files": "رفع الملفات",
  "select_category": "اختر الفئة",
  "completed_success": "اكتمل بنجاح",
  "change_password": "تغيير كلمة المرور",
  "first_category": "قم بإنشاء الفئة الأولى الخاصة بك",
  "background_category": "خلفية الفئة",
  "categories": "الاقسام",
  "display_images": "عرض الصور من السحابة",
  "display_files": "ملفات من السحابة",
  "delete_image": "هل أنت متأكد أنك تريد حذف هذه الصورة؟",
  "select_files": "اختر الملفات",
  "favorites": "المفضلة",
  "sign_out": "تسجيل الخروج",
  "delete_category": "حذف الفئة",
  "about_app": "حول بوب كورن",
  "no_favorites": "لا مفضلات حتى الآن!",
  "restart": "إعادة تشغيل",
  "reset": "إعادة تعيين",
  "start_again": "ابدأ مرة أخرى في البداية",
  "terms_service": "شروط الخدمة",
  "terms_content": "بالنقر فوق تسجيل ، فإنك تشير إلى أنك قد قرأت ووافقت على",
  "select_image": "حدد صورة من هاتفك",
  "auth_required": "المصادقة مطلوبة ، تحتاج إلى تسجيل الدخول إلى حسابك",
  "have_account": "هل لديك حساب؟",
  "notifications": "إشعارات",
  "profile": "الملف الشخصي",
  "birthday": "عيد ميلاد",
  "not_over_16": "آسف! لم يتجاوز عمرك 16 عامًا",
  "iam_over_16": "عمري يزيد عن 16 سنة",
  "confirm_age": "يرجى تأكيد أن عمرك لا يقل عن 16 عامًا للمتابعة",
  "upload_profile_pic": "قم بتحميل صورة ملفك الشخصي",
  "photo_library": "مكتبة الصور",
  "take_photo": "التقط صورة",
  "crop_rotate": "اقتصاص وتدوير",
  "posts": "مشاركات",
  "follower": "متابعون",
  "following": "يتابع",
  "need_help": "انا بحاجة الى مساعدة",
  "settings": "الإعدادات",
  "safety_center": "مركز الأمان",
  "feedback": "الإبلاغ عن الأخطاء",
  "version": "إصدار %s",
  "rate_app": "قيم التطبيق",
  "username_short": "اسم المستخدم قصير جدا",
  "username_long": "اسم المستخدم طويل جدا",
  "on_your_mind": "ماذا يدور بعقلك؟",
  "submit": "إرسال",
  "write": "اكتب",
  "male": "ذكر",
  "female": "أنثى",
  "other": "آخر",
  "no_gender": "لم يتم تحديد الجنس",
  "add_bio": "إضافة سيرتي الذاتية",
  "edit_profile": "تعديل الملف الشخصي",
  "follow_user": "اتبع المستخدم",
  "send_message": "أرسل رسالة",
  "no_more_posts": "لا يوجد المزيد من الوظائف لعرضها الآن",
  "enjoy_life": "استمتع بحياتك الجيدة من الآن!",
  "room": "غرفة",
  "moments": "لحظات",
  "message": "رسائل",
  "visitors": "الزائرين",
  "save": "حفظ",
  "language": "اللغة",
  "push_notify": "دفع الإخطارات",
  "privacy": "خصوصية",
  "blocked_list": "قائمة المحظورين",
  "dark_mode": "الوضع المظلم",
  "clear_cache": "مسح ذاكرة التخزين المؤقت",
  "clear_records": "محو سجلات الدردشة",
  "network_test": "اختبار الشبكة",
  "about": "حول",
  "related": "ذات صلة",
  "explore": "استكشف",
  "all": "الكل",
  "Tasks": "المهام",
  "wallet": "المحفظة",
  "store": "المتجر",
  "level": "المستوى",
  "faq_feedback": "التعليمات والتعليقات",
  "start_following": "ابدأ في متابعة الأشخاص الآن.",
  "nobody_following": "لا أحد يتابعك.",
  "edit": "تعديل",
  "track": "المسار",
  "badge": "شارة",
  "gift": "هدية",
  "topics": "موضوع",
  "featured": "متميز",
  "create_my_room": "إنشاء غرفتي",
  "create_room": "إنشاء غرفة",
  "start_journey": "ابدأ رحلتك على بوب كورن",
  "room_name": "اسم الغرفة",
  "announcement": "إعلان",
  "create_free": "أنشئ مجانًا",
  "joined": "انضم",
  "recently": "حديثا",
  "ann_text": "مرحبًا بالجميع! دعنا نتحادث ونستمتع معا.",
  "popular": "شائع",
  "new": "جديد",
  "id_room": "ID: %s",
  "not_alone": "انت لست وحدك",
  "log_in": "تسجيل الدخول",
  "first_name": "الاسم الأول",
  "last_name": "الاسم الاخير",
  "wrong_password": "كلمة مرور خاطئة",
  "email_not_found": "لا يوجد سجل مستخدم حالي مطابق للبريد الإلكتروني المقدم",
  "forgot_password": "هل نسيت كلمة السر",
  "enter_your_email": "أدخل بريدك الإلكتروني وسوف نرسل لك تعليمات حول كيفية إعادة تعيينه",
  "oops": "عفوا!",
  "phone_auth": "مصادقة الهاتف",
  "phone_authentic": "مصادقة الهاتف",
  "phone_not_valid": "رقم الهاتف غير صالح",
  "verify_code": "رمز التحقق",
  "verify": "التحقق",
  "invalid_code": "الرمز غير صحيح",
  "verify_phone": "تحقق من %s",
  "type_something": "اكتب شيئا",
  "become_member": "كن عضوًا لأخذ الميكروفون. \n انضم مجانًا؟",
  "join": "انضم",
  "invites_use_mic": "%s يدعوك لاستخدام الميكروفون",
  "accept": "قبول",
  "ignore": "يتجاهل",
  "try_again": "حاول مجددا",
  "file_not_supported": "الملف غير مدعوم",
  "payment_cancelled": "تم إلغاء الدفع",
  "pay_successful": "تم الدفع بنجاح",
  "show_order_details": "إظهار تفاصيل الطلب",
  "manage_subscription": "Manage Subscription",
  "current_plan": "Current Plan",
  "upgrade": "Upgrade",
  "subscribe": "Subscribe",
  "unsubscribe": "Unsubscribe",
  "time_period": "Time Period",
  "payment": "Payment",
  "failed_register_customer": "Failed to register as a customer",
  "failed_update_customer": "Failed to update Customer",
  "failed_register_subscriber": "Failed to register as a subscriber.",
  "failed_attach_payment": "Failed to attach PaymentMethod",
  "failed_create_payment": "Failed to create PaymentMethod",
  "10_posts_day": "10 posts per day to a Gen Z audience",
  "find_candidates_customers": "Find candidates and customers",
  "success": "Success",
  "number": "Number",
  "actively": "نشط",
  "banned": "محظور",
  "archive": "أرشيف",
  "user_cancelled_login": "ألغى المستخدم تسجيل الدخول مع %s",
  "display_name": "اسمك الكامل",
  "manage_gifts": "Manage gifts",
  "manage_topics": "Manage topics",
  "manage_border_frames": "إدارة الإطارات",
  "send_notify_to_all": "إرسال الإخطارات للجميع",
  "please_choose_topic": "الرجاء اختيار الموضوع",
  "no_results_found": "لم يتم العثور على نتائج",
  "add_topic": "إضافة موضوع",
  "delete_topic": "حذف الموضوع",
  "delete_topic_msg": "هل أنت متأكد أنك تريد حذف هذا الموضوع؟",
  "name_topic": "اسم الموضوع",
  "successfully_uploaded": "تم الرفع بنجاح",
  "delete_img": "حذف صورة",
  "delete_img_msg": "هل أنت متأكد أنك تريد حذف هذه الصورة؟",
  "gifts": "الهدايا",
  "frames": "الإطارات",
  "gifts_week": "هدايا الأسبوع",
  "everyoneOnMic": "الجميع على الميكروفون",
  "take_mic": "خذ الميكروفون",
  "lock_mic": "اقفل الميكروفون",
  "defaultWelcomeMessage": "نرحب عن ترحيبنا الحار بكم احصل على الميكروفون ودعنا نتحدث .",
  "keep": "احتفظ",
  "exit": "خروج",
  "attendance": "الحضور %s",
  "send_gifts": "أرسل هدايا",
  "magic_card": "بطاقة سحرية",
  "mute_mic": "كتم ميكروفون",
  "add_friend": "أضف صديق",
  "unfollow": "الغاء المتابعة",
  "user_not_found2": "لم يتم العثور على المستخدم",
  "report_block": "الإبلاغ أو الحظر",
  "report_post_msg_comment": "الإبلاغ عن مشاركة أو رسالة أو تعليق",
  "report_account": "الإبلاغ عن الحساب",
  "posts_comments": "المشاركات أو التعليقات",
  "messages": "الرسائل",
  "report_content_profile": "الإبلاغ عن محتوى في ملف التعريف",
  "block_account": "حظر %s",
  "profile_info": "معلومات الملف الشخصي",
  "background_profile_photo": "الخلفية أو صورة الملف الشخصي",
  "submitted_report": "قدم إلى Popcorn للمراجعة",
  "last_seen": "آخر ظهور %s",
  "online": "متصل",
  "uploading_photo": "جارٍ تحميل الصور ..",
  "photo_profile": "الصورة الشخصية",
  "account_created": "Popcorn > %s",
  "bio": "السيرة الذاتية",
  "enter_your_date_birth": "أدخل تاريخ ميلادك",
  "welcome_new_members": "نرحب بالأعضاء الجدد!",
  "members": "الأعضاء",
  "events": "الأحداث",
  "edit_room": "تحرير غرفة",
  "verify_link_sent_your_email": "تم إرسال رابط التحقق إلى عنوان بريدك الإلكتروني!",
  "register_by_email": "التسجيل عن طريق البريد الإلكتروني",
  "or": " أو",
  "continue_google": "سجل مع جوجل",
  "continue_apple": "سجل مع أبل",
  "continue_facebook": "سجل مع فيسبوك",
  "agree_terms_service": "من خلال الاستمرار فإنك توافق على",
  "terms_of_use": "شروط الاستعمال",
  "by_sawwl": "بواسطة Sawwl",
  "terms_of_service": "شروط الخدمة",
  "already_have_account": "هل لديك حساب",
  "email": "بريد إلكتروني",
  "dont_have_account_yet": "لا تملك حسابا حتى الآن؟",
  "full_name": "الإسم واللقب",
  "birthdate": "تاريخ الميلاد",
  "enter_valid_email": "أدخل عنوان بريد إلكتروني صالح",
  "pls_select_gender": "يرجى تحديد الجنس",
  "confirm_password": "تأكيد كلمة السر",
  "please_select_room_photo": "الرجاء اختيار صورة الغرفة",
  "choose_background_image": "اختر صورة الخلفية",
  "remove_background_image": "إزالة صورة الخلفية",
};