
const Map<String, String> en = {
  "app_name": "Popcorn",
  "error_wrong": "Something went wrong try again later",
  "my_account": "My Account",
  "sign_in": "Sign in",
  "sign_in_google": "Sign in with google",
  "sign_in_facebook": "Sign in with facebook",
  "sign_with_email": "Sign in with Email",
  "sign_up_google": "Sign up with google",
  "sign_up_facebook": "Sign up with facebook",
  "something_wrong": "Oops! something went wrong",
  "welcome": "Welcome %s",
  "line_or": "or",
  "forgot_pass": "Forgot your password?",
  "password": "Password",
  "required_field": "Required field",
  "required_field_for": "Required field %s",
  "email_address": "Email address",
  "user_not_found": "No user found for that email",
  "email_valid": "Enter a valid email address",
  "sign_up_free": "Sign up for free",
  "new_account": "Register a new account",
  "your_name": "Your name",
  "phone_number": "Your phone number",
  "create_account": "Create an account",
  "cancel": "Cancel",
  "weak_password": "The password is too weak",
  "email_already_use": "The account already exists for that email",
  "pass_not_correct": "Password not correct",
  "reset_pass": "Reset Password",
  "send_reset_link": "Send reset link",
  "send": "Send ",
  "reset_password": "Reset your password",
  "check_email": "Check your email address",
  "home": "Home",
  "update_account": "Update account",
  "update_success": "Update successfully",
  "old_pass": "Old password",
  "new_pass": "New password",
  "old_email": "Old email address",
  "new_email": "New email address",
  "update_email": "Update email address",
  "update": "Update",
  "recent_login": "This operation is sensitive and requires recent authentication. Log in again before retrying this request.",
  "update_pass": "Update password",
  "old_pass_not_correct": "Your old password not correct",
  "next": "Next",
  "back": "Back",
  "select_photos": "Select photos",
  "select_photo": "Select a photo",
  "price": "Price",
  "error_connection": "No internet connection. Make sure Wi-Fi or cellular data is turned on, then try again",
  "login_required": "Login required",
  "delete_optional": "Delete optional",
  "delete": "Delete",
  "active_since": "Active since %s",
  "my_favorite": "My Favorite",
  "search": "Search",
  "not_found": "We couldn't find what you were looking for",
  "validate": "Validate",
  "filters": "Filters",
  "all_photos": "All Photos",
  "email_invalid": "Email address is invalid",
  "login": "Login",
  "sign_up": "Sign Up",
  "skip": "Skip",
  "get_start": "Get Started Now",
  "intro_1": "Hello! \uD83D\uDC4B",
  "intro_2": "App for those who are going through difficult times and can't share it with anyone",
  "intro_3": "Support \uD83D\uDE4F",
  "intro_4": "Support is something that helps you survive and not give up. Community inside the OutLoud can help to reduce feelings of loneliness and help you to feel understood",
  "intro_5": "Psychology \uD83E\uDDE0",
  "intro_6": "From a psychological point of view, writing out your problems and crisis situations helps you manage with them at least emotionally",
  "intro_7": "Anonymous \uD83E\uDDB8",
  "intro_8": "To keep incognito or openly talk about your problem - it's only up to you. Your anonymity is guaranteed",
  "dont_have_account":"don't have an account yet?",
  "register": "Register",
  "exit_app": "Are you sure you want to Exit?",
  "logout_app": "Are you sure you want to Logout?",
  "no": "No",
  "yes": "Yes",
  "account": "Account",
  "info": "Information",
  "favorite": "Favorite",
  "how_to_use":"How to use Pop Corn?",
  "category": "Category",
  "admin": "Admin",
  "upload_images": "Upload Images",
  "upload_files": "Upload Files",
  "select_category": "Select Category",
  "completed_success": "Completed Successfully",
  "change_password": "Change Password",
  "first_category": "Create your first category",
  "background_category": "Background Category",
  "categories": "Categories",
  "display_images": "Display Images From Cloud",
  "display_files": "Files From Cloud",
  "delete_image": "Are you sure you want to delete this image?",
  "select_files": "Select Files",
  "favorites": "Favorites",
  "sign_out": "Sign out",
  "delete_category": "Delete category",
  "about_app": "About Pop Corn",
  "no_favorites": "No Favorites Yet!",
  "restart": "Restart",
  "reset": "Reset",
  "start_again": "Start again at the beginning",
  "terms_service": "Terms of Service",
  "terms_content": "By clicking Sign Up, you are indicating that you have read and agree to the",
  "select_image": "Select image from your gallery",
  "auth_required": "Authentication is required, you need to sign into your account",
  "have_account": "Already have an account?",
  "notifications": "Notifications",
  "profile": "Profile",
  "birthday": "Birthday",
  "not_over_16": "Sorry!, you are not over 16 years of age",
  "iam_over_16": "I am over 16 years of age",
  "confirm_age": "Please confirm you are at least 16 years old to continue",
  "upload_profile_pic": "Upload your profile picture",
  "photo_library": "Photo Library",
  "take_photo": "Take Photo",
  "crop_rotate": "Crop and rotate",
  "posts": "Posts",
  "follower": "Followers",
  "following": "Following",
  "need_help": "I need Help",
  "settings": "Settings",
  "safety_center": "Safety Center",
  "feedback": "Feedback",
  "version": "Version %s",
  "rate_app": "Rate App",
  "username_short": "Username is very short",
  "username_long": "Username is very long",
  "on_your_mind": "What's on your mind?",
  "submit": "Submit",
  "write": "Write",
  "male": "Male",
  "female": "Female",
  "other": "Other",
  "no_gender": "No gender selected",
  "add_bio": "Add my biography",
  "edit_profile": "Edit Profile",
  "follow_user": "Follow User",
  "send_message": "Send Message",
  "no_more_posts": "There are no more posts to show right now",
  "enjoy_life":"Enjoy your good life from now!",
  "room": "Room",
  "moments": "Moments",
  "message": "Message",
  "visitors": "Visitors",
  "save": "Save",
  "language": "Language",
  "push_notify": "Push Notifications",
  "privacy": "Privacy",
  "blocked_list": "Blocked List",
  "dark_mode": "Dark Mode",
  "clear_cache": "Clear Cache",
  "clear_records": "Clear Chatting Records",
  "network_test": "Network Test",
  "about": "About",
  "related": "Related",
  "explore": "Explore",
  "all": "All",
  "tasks": "Tasks",
  "wallet": "Wallet",
  "store": "Store",
  "level": "Level",
  "faq_feedback": "FAQ & Feedback",
  "start_following": "Start following people now.",
  "nobody_following": "Nobody is following you",
  "edit": "Edit",
  "track": "Track",
  "badge": "Badge",
  "gift": "Gift",
  "topics": "Topics",
  "featured": "Featured",
  "create_my_room": "Create My Room",
  "create_room": "Create Room",
  "start_journey": "Start your journey on PopCorn",
  "room_name": "Room Name",
  "announcement": "Announcement",
  "create_free": "Create for Free",
  "joined": "Joined",
  "recently": "Recently",
  "ann_text": "Welcome everyone! Let's chat and have fun together.",
  "popular": "Popular",
  "new": "New",
  "id_room": "ID: %s",
  "not_alone": "You are not alone",
  "log_in": "Log in",
  "first_name": "First name",
  "last_name": "Last name",
  "wrong_password": "Wrong password",
  "email_not_found": "There is no existing user record corresponding to the provided email",
  "forgot_password": "Forgot Password",
  "enter_your_email": "Enter your email and will send you instruction on how to reset it",
  "oops": "Oops!",
  "phone_auth": "Phone Auth",
  "phone_authentic": "Phone Authentication",
  "phone_not_valid": "Phone number is not valid",
  "verify_code": "Verification Code",
  "verify": "Verify",
  "invalid_code": "Invalid code",
  "verify_phone": "Verify %s",
  "type_something": "Type Something...",
  "become_member": "Become member to take the mic.\nJoin for free?",
  "join": "Join",
  "invites_use_mic": "%s invites you to use the mic",
  "accept": "Accept",
  "ignore": "Ignore",
  "try_again": "Try again",
  "file_not_supported": "File is not supported",
  "payment_cancelled": "Payment cancelled",
  "pay_successful": "Payment Successful",
  "show_order_details": "Show order details",
  "manage_subscription": "Manage Subscription",
  "current_plan": "Current Plan",
  "upgrade": "Upgrade",
  "subscribe": "Subscribe",
  "unsubscribe": "Unsubscribe",
  "time_period": "Time Period",
  "payment": "Payment",
  "failed_register_customer": "Failed to register as a customer",
  "failed_update_customer": "Failed to update Customer",
  "failed_register_subscriber": "Failed to register as a subscriber.",
  "failed_attach_payment": "Failed to attach PaymentMethod",
  "failed_create_payment": "Failed to create PaymentMethod",
  "10_posts_day": "10 posts per day to a Gen Z audience",
  "find_candidates_customers": "Find candidates and customers",
  "success": "Success",
  "number": "Number",
  "actively": "Actively",
  "banned": "Banned",
  "archive": "Archive",
  "user_cancelled_login": "User has cancelled login with %s",
  "display_name": "Display name",
  "manage_gifts": "Manage gifts",
  "manage_topics": "Manage topics",
  "manage_border_frames": "Manage border frames",
  "send_notify_to_all": "Send notifications to all",
  "please_choose_topic": "Please choose topic",
  "no_results_found": "No results found",
  "add_topic": "Add topic",
  "delete_topic": "Delete topic",
  "delete_topic_msg": "Are you sure you want to delete this topic?",
  "name_topic": "Name topic",
  "successfully_uploaded": "Successfully uploaded",
  "delete_img": "Delete image",
  "delete_img_msg": "Are you sure you want to delete this image?",
  "gifts": "Gifts",
  "frame": "Frame",
  "gifts_week": "Gifts of the week",
  "everyoneOnMic": "Everyone on Mic",
  "take_mic": "Take the mic",
  "lock_mic": "Lock the mic",
  "defaultWelcomeMessage": "We extend our hearty welcome to you. Grab a mic and let's have some talk",
  "keep": "Keep",
  "exit": "Exit",
  "attendance": "Attendance %s",
  "send_gifts": "Send Gifts",
  "magic_card": "Magic Card",
  "mute_mic": "Mute Mic",
  "add_friend": "Add Friend",
  "unfollow": "Unfollow",
  "user_not_found2": "User not found",
  "report_block": "Report or block",
  "report_post_msg_comment": "Report Post, Message or Comment",
  "report_account": "Report Account",
  "posts_comments": "Posts or comments",
  "messages": "Messages",
  "report_content_profile": "Report content on profile",
  "block_account": "Block %s",
  "profile_info": "Profile Information",
  "background_profile_photo": "Background or profile photo",
  "submitted_report": "Submitted to Popcorn for review",
  "last_seen": "Last seen %s",
  "online": "Online",
  "uploading_photo": "Uploading photos..",
  "photo_profile": "Photo profile",
  "account_created": "Popcorn > %s",
  "bio": "Bio",
  "enter_your_date_birth": "Entrez votre date de naissance",
  "welcome_new_members": "Welcome New Members!",
  "members": "Members",
  "events": "Events",
  "edit_room": "Edit Room",
};