// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrT8IEWhesUENTx0P1wXFCSwJYmxz7VX4',
    appId: '1:320913010853:web:97ca94820703e6c4e15d4c',
    messagingSenderId: '320913010853',
    projectId: 'popcorn-e7b6a',
    authDomain: 'popcorn-e7b6a.firebaseapp.com',
    storageBucket: 'popcorn-e7b6a.appspot.com',
    measurementId: 'G-CQSNQ2H011',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjhdMWcJX3nOr6mPFclJgvHfpx8eVN7Ss',
    appId: '1:320913010853:android:0f3521a6f6d002a1e15d4c',
    messagingSenderId: '320913010853',
    projectId: 'popcorn-e7b6a',
    storageBucket: 'popcorn-e7b6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCVhTeT4DYHV_Ry3i3Dyot9L7xZ4Anmn0',
    appId: '1:320913010853:ios:219a09f4f76d239ee15d4c',
    messagingSenderId: '320913010853',
    projectId: 'popcorn-e7b6a',
    storageBucket: 'popcorn-e7b6a.appspot.com',
    androidClientId: '320913010853-0te2uoe7gqgf4aimf4cvqr4cqioumguo.apps.googleusercontent.com',
    iosClientId: '320913010853-6m87f0eb44k7o95e746kc4e1c8qj41o6.apps.googleusercontent.com',
    iosBundleId: 'com.chat.popcorn',
  );
}
